<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260728124614 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Tworzy tabele book i loan wraz z partial unique index '
            .'loan_one_active_per_book (book_id) WHERE returned_at IS NULL, '
            .'który wymusza w bazie, że książka może mieć co najwyżej jedno '
            .'aktywne (niezwrócone) wypożyczenie naraz — nawet przy dwóch '
            .'równoległych żądaniach wypożyczenia.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE book (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, serial_number VARCHAR(6) NOT NULL, title VARCHAR(255) NOT NULL, author VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX book_serial_number_unique ON book (serial_number)');
        $this->addSql('CREATE TABLE loan (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, returned_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, card_number VARCHAR(6) NOT NULL, borrowed_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, book_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C5D30D0316A2B381 ON loan (book_id)');
        $this->addSql('ALTER TABLE loan ADD CONSTRAINT FK_C5D30D0316A2B381 FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX loan_one_active_per_book ON loan (book_id) WHERE returned_at IS NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX IF EXISTS loan_one_active_per_book');
        $this->addSql('ALTER TABLE loan DROP CONSTRAINT FK_C5D30D0316A2B381');
        $this->addSql('DROP TABLE book');
        $this->addSql('DROP TABLE loan');
    }
}
